# Netlify configuration for Vite build output and SPA routing

[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

# SPA routing: catch-all redirect to index.html for client-side routing
# This ensures React Router handles all routes on the client side
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache headers for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"