[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_BASE_URL = "https://portfolio-backend-latest.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.development]
[build.environment]
  VITE_API_BASE_URL = "http://localhost:3001/api"

[context.branch-deploy]
[build.environment]
  VITE_API_BASE_URL = "https://portfolio-backend-latest.onrender.com/api"